### ISSUE TITLE
Compounding not working

### ISSUE THREAD

**Issue by GeminiSquishGames** [Seva167/PMAPI#3]
Blue Slime (Slime) and rood don't compound to make blud, nor can I get my own objects to compound. Unless I'm doing it wrong but I assume it's like anything else that you mix by hand.

**Comment by Secretname2009** [comment]
Basically the line "CubeMerge.compoundablePairs.Add(new Il2CppSystem.ValueTuple<Substance, Substance>(ExampleSubstance1, ExampleSubstance2), new Il2CppSystem.ValueTuple<float, Substance, float>(1f, ResultSubstance, 1f));" can only be used once shared by all mods. Ive tried to find a fix and a workaround for this issue. but i have not found either yet. This prevents Compounding from being used in mods and only one mod can use it once.

**Comment by Seva167** [comment]
Can't replicate the issue, compounding works from all mods and with all substances, perhaps you've just copied code from TestMod without changing it and it caused exception because this compound pair already exists.

**Comment by GeminiSquishGames** [comment]
If a compound pair exists or you try to overwrite it, it shows the error in MelonLoader console so I learned about that, I simply added a substance, got it to show up, and then tried to make red slime and blue slime combine as a different pair and they just snapped together, no errors in console, but I was simply trying to piggy back off the mod by adding stuff to it's source, not copying it as such. So I tried rebuilding the .dll from the test mod fresh from the .zip source and tried to combine slime and rood and they just snap together.

**Comment by Secretname2009** [comment]
The game shows an ArgumentException regardless of what you put in the second CompoundablePairs line. It could be entirely different and yet it will throw ArgumentException. This applies to all subsequent mods if they also use this line, they will error on their CompoundablePairs lines. Ive already tested this and tried to figure out a workaround or a fix but im not good enough at CSharp to understand ValueTuple and why it doesnt change regardless of combination. 
Below is an example that ive tested and replicated the issue with along with the entire .cs file pasted into here.

The lines are:`CubeMerge.compoundablePairs.Add(new Il2CppSystem.ValueTuple<Substance, Substance>(Substance.DryGrass, Substance.Slime), new Il2CppSystem.ValueTuple<float, Substance, float>(1f, blud, 1f));`
and `CubeMerge.compoundablePairs.Add(new Il2CppSystem.ValueTuple<Substance, Substance>(Substance.Wood, Substance.RedSlime), new Il2CppSystem.ValueTuple<float, Substance, float>(1f, rood, 1f));`

They are both different and yet the second line fails to register with this error:
`[12:18:06.676] [Test_Mod] Il2CppInterop.Runtime.Il2CppException: System.ArgumentException: An item with the same key has already been added. Key: (-512778464, 400)
--- BEGIN IL2CPP STACK TRACE ---
System.ArgumentException: An item with the same key has already been added. Key: (-512778464, 400)
  at System.Collections.Generic.Dictionary`2[TKey,TValue].TryInsert (TKey key, TValue value, System.Collections.Generic.InsertionBehavior behavior) [0x00000] in <00000000000000000000000000000000>:0
  at System.Collections.Generic.Dictionary`2[TKey,TValue].Add (TKey key, TValue value) [0x00000] in <00000000000000000000000000000000>:0
--- END IL2CPP STACK TRACE ---

   at Il2CppInterop.Runtime.Il2CppException.RaiseExceptionIfNecessary(IntPtr returnedException) in /home/runner/work/Il2CppInterop/Il2CppInterop/Il2CppInterop.Runtime/Il2CppException.cs:line 36
   at Il2CppSystem.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at TestMod.TestMod.RegisterRood()
   at TestMod.TestMod.OnInitializeMelon()
   at MelonLoader.MelonBase.LoaderInitialized() in D:\a\MelonLoader\MelonLoader\MelonLoader\Melons\MelonBase.cs:line 440`

For completion, here is the entire code that was tested and built. It does not have to be this specific code, even if the CompoundablePairs line has different combination and result, it will fail on the second attemt at adding something to it.
`using MelonLoader;
using Il2Cpp;
using PMAPI;
using UnityEngine;
using Il2CppInterop.Runtime.Injection;
using PMAPI.CustomSubstances;
using PMAPI.OreGen;
using UnityEngine.SceneManagement;
using System.Text.Json;

namespace TestMod
{
    public class TestMod : MelonMod
    {
        // Mod data class
        public class OurData
        {
            public int Test { get; set; }

            public OurData(int test)
            {
                Test = test;
            }
        }

        Substance blud;
        Substance rood;

        public override void OnInitializeMelon()
        {
            // Init PMAPI
            PMAPIModRegistry.InitPMAPI(this);

            // Register in our behaviour in IL2CPP so the game knows about it
            ClassInjector.RegisterTypeInIl2Cpp<TestBeh>(new RegisterTypeOptions
            {
                Interfaces = new[] { typeof(ICubeBehavior), typeof(ISavable) }
            });
            CustomOreManager.RegisterCustomOre(blud, new CustomOreManager.CustomOreParams
            {
                chance = 0.1f,
                substanceOverride = Substance.Stone,
                maxSize = 0.3f,
                minSize = 0.3f,
                alpha = 1f
            });
            RegisterBlud();
            RegisterRood();

            // Registering our substances in ore generation
            CustomOreManager.RegisterCustomOre(blud, new CustomOreManager.CustomOreParams
            {
                chance = 0.1f,
                substanceOverride = Substance.Stone,
                maxSize = 0.3f,
                minSize = 0.3f,
                alpha = 1f
            });
            CustomOreManager.RegisterCustomOre(rood, new CustomOreManager.CustomOreParams
            {
                chance = 0.1f,
                substanceOverride = Substance.Stone | Substance.MoonRock,
                maxSize = 0.3f,
                minSize = 0.3f,
                alpha = 1f
            });
        }

        // Gets called just when the world was loaded
        public void OnWorldWasLoaded()
        {
            // Outputting mod data. The question mark means that nothing will be outputted if mod data doesn't exist (data == null)
            MelonLogger.Msg("Mod data is {0}", ExtDataManager.GetData<OurData>()?.Test);
        }

        // Omg!!1!!11 Blue wood leaf
        void RegisterBlud()
        {
            // Getting wood material and coloring it BLUE
            Material cmat = new(SubstanceManager.GetMaterial("Wood"))
            {
                name = "Blud",
                color = Color.blue
            };
            // Registering material
            CustomMaterialManager.RegisterMaterial(cmat);

            // Getting substance params that our substance is based on and modifying them
            var param = SubstanceManager.GetParameter(Substance.Leaf).MemberwiseClone().Cast<SubstanceParameters.Param>();

            // Should be unique
            param.displayNameKey = "SUB_BLUD";
            param.material = cmat.name;

            // Registering our substance as custom substance
            blud = CustomSubstanceManager.RegisterSubstance("blud", param, new CustomSubstanceParams
            {
                enName = "Blud",
                ruName = "Синево",
                zhHansName = "zhHansName",
                deName = "deName",
                esName = "esName",
                frName = "frName",
                jpName = "name2",
                behInit = (cb) =>
                {
                    // Adding test behavior
                    var beh = cb.gameObject.AddComponent<TestBeh>();
                    return beh;
                }
            });
            CubeMerge.compoundablePairs.Add(new Il2CppSystem.ValueTuple<Substance, Substance>(Substance.DryGrass, Substance.Slime), new Il2CppSystem.ValueTuple<float, Substance, float>(1f, blud, 1f));
        }

        // Red wood bruh
        void RegisterRood()
        {
            Material cmat = new(SubstanceManager.GetMaterial("Wood"))
            {
                name = "Rood",
                color = Color.red
            };
            CustomMaterialManager.RegisterMaterial(cmat);

            var param = SubstanceManager.GetParameter(Substance.Wood).MemberwiseClone().Cast<SubstanceParameters.Param>();
            param.displayNameKey = "SUB_ROOD";
            param.material = cmat.name;
            rood = CustomSubstanceManager.RegisterSubstance("rood", param, new CustomSubstanceParams
            {
                enName = "Rood",
                ruName = "Кререво",
                jpName = "name3"
            });

            // Make rood and blue slime compoundable to form blud
            CubeMerge.compoundablePairs.Add(new Il2CppSystem.ValueTuple<Substance, Substance>(Substance.Wood, Substance.RedSlime), new Il2CppSystem.ValueTuple<float, Substance, float>(1f, rood, 1f));
        }

        public override void OnUpdate()
        {
            // Spawning blud above our head
            if (Input.GetKeyDown(KeyCode.L))
            {
                // Getting player position
                var mv = GameObject.Find("XR Origin").GetComponent<PlayerMovement>();

                // Generating the cube
                CubeGenerator.GenerateCube(mv.cameraTransform.position + new Vector3(0f, 10f, 1f), Vector3.one, blud);
            }

            // Writing test data that will be stored in save file
            if (Input.GetKeyDown(KeyCode.X))
                ExtDataManager.SetData(new OurData(UnityEngine.Random.RandomRangeInt(1, 100)));
        }
    }

    public class TestBeh : MonoBehaviour
    {
        public TestBeh(IntPtr ptr) : base(ptr)
        {
            // Requesting load of cube save data
            CustomSaveManager.RequestLoad(this);
        }

        CubeBase cubeBase;

        void OnInitialize()
        {
            // Get the cube base
            cubeBase = GetComponent<CubeBase>();

            // Make it hooooooot
            cubeBase.heat.AddHeat(1000000f);
        }

        // Saved variable
        Data data = new("test123");

        // When cube is going to save it's data return the data that we want to save
        public string Save()
        {
            // Serialize into JSON
            return JsonSerializer.Serialize(data);
        }

        // When cube is loaded set our variable to loaded data
        public void Load(string json)
        {
            // From JSON to Data
            data = JsonSerializer.Deserialize<Data>(json);
        }

        public class Data
        {
            public string SomeString { get; set; }

            public Data(string someString)
            {
                SomeString = someString;
            }
        }
    }
}`

**Comment by Secretname2009** [comment]
Is there any update on this problem? A mod im making is on hold until this is solved or a workaround is found but as far as ive experimented, i have not found a good workaround myself yet.

**Comment by Seva167** [comment]
This isn't even PMAPI function. ValueTuple just stores multiple numbers in 1 object while acting just like value type. The dictionary just contains substance pair to result connection and whenever 2 cubes are combined, game checks if their pair exists in the dictionary and compounds them if it does. This problem doesn't look like PMAPI related or Primitier related, but this may be il2cpp limitation. Try making a mod that doesn't use PMAPI and just add a new compound pair for existing substances. And try not to copy and paste TestMod, instead try making your own test code.
